---
- name: Check install dir exists
  file:
    path: "{{ maven_install_dir }}"
    state: directory

- name: download maven binaries
  get_url:
    url: "{{ maven_download_url }}"
    dest: "{{ maven_install_dir }}"

- name: Unarchive Maven Binaries
  unarchive:
    src: '{{ maven_install_dir }}/{{ maven_file_name }}'
    dest: '{{ maven_install_dir }}'
    copy: no
    extra_opts: "--strip-components=1"

- name: Remove previous Maven scripts
  file:
    path: /etc/profile.d/maven.sh
    state: absent

- name: Create Maven script
  lineinfile:
    dest: /etc/profile.d/maven.sh
    line: "{{ item.line }}"
    create: yes
    state: present
    mode: 0755
  with_items:
    - { line: "# Apache Maven Environment Variables" }
    - { line: "# Create by Ansible Role" }
    - { line: "export M2_HOME={{ maven_install_dir }}" }
    - { line: "export PATH=$PATH:$M2_HOME/bin" }

- name: Clear up downloaded maven binary
  file:
    path: "{{ maven_install_dir }}/{{ maven_file_name }}"
    state: absent

# install java jdk for maven and update .mavenrc 
- name: Install java using yum
  yum:
    name: java-1.8.0-openjdk-devel
    state: present

# TODO: setup $JAVA_HOME for maven 