---
- name: Check install dir exists
  file:
    path: "{{ maven_install_dir }}"
    state: directory

- name: download maven binaries
  get_url:
    url: "{{ maven_download_url }}"
    dest: "{{ maven_install_dir }}"

- name: Unarchive Maven Binaries
  unarchive:
    src: '{{ maven_install_dir }}/{{ maven_file_name }}'
    dest: '{{ maven_install_dir }}'
    copy: no
    extra_opts: "--strip-components=1"
  

- name: Clear up downloaded maven binary
  file:
    path: "{{ maven_install_dir }}/{{ maven_file_name }}"
    state: absent